opensearch:
  index_name: "flibusta_merged_index"
  url: "http://cloud-1:9200"

paths:
  warn_dir: "./data/warn"
  output_dir: "./data/out"
  source_dir: "/mnt/fb2/fb2.Flibusta.Net"

processing:
  threads: 4

logging:
  log_path: "f2bulker.log"

metrics:
  pushgateway_url: "http://localhost:9091"

# Пауза в секундах между архивами, чтобы сервер остыл
sleep_between_zips: 600 


uploading:
  log_path: "uploader.log"
  sleep_between_uploads: 30
